### ISSUE TITLE
Unable to connect to Inertia SSR server and 404. How to debug?

### ISSUE THREAD

**Issue by harryqt** [onix-systems-php/hyperf-inertia#15]
I've managed to set it up with Svelte and everything seems to work fine when using `bun run dev` 👍 , but facing issues when using SSR. Building works fine.

<img width="1469" alt="Screenshot 2024-07-20 at 1 15 10 PM" src="https://github.com/user-attachments/assets/edcd1a54-0592-472f-8c47-79350d25924e">

When I run: `php ./bin/hyperf.php inertia:start-ssr --runtime=bun` it shows `Unable to connect to Inertia SSR server` but it actually works fine.

<img width="1469" alt="Screenshot 2024-07-20 at 1 15 39 PM" src="https://github.com/user-attachments/assets/d59d6d11-ed56-4db9-812a-d0c24480a84d">

I can see app is serving SSR-ed content but client side hydration does not work because of 404s.

<img width="1582" alt="Screenshot 2024-07-20 at 1 17 21 PM" src="https://github.com/user-attachments/assets/41c7936c-949e-41de-85df-16419206e21e">

`.env` contains

```
INERTIA_IS_SECURE=false
INERTIA_SSR_ENABLED=true
```

**Comment by harryqt** [comment]
@vmikhav On ssr mode app the app not correctly serving public directory. How can I fix?

**Comment by tahyhax** [comment]
@harryqt Provide your  .env

**Comment by harryqt** [comment]
Check out repro: https://github.com/harryqt/hyperf-inertia-test/blob/main/.env

**Comment by tahyhax** [comment]
@harryqt Do you have nodejs and npm installed on your server?  If not, install them

**Comment by harryqt** [comment]
`npm run build` builds the app successfully but upon browsing the js files throws 404.

Such as `http://127.0.0.1:9501/public/build/assets/app-ClBELM2y.js` ---> this 404

Which is expected, because it actually stored in `/storage/public/build/assets/app-ClBELM2y.js`

<img width="1582" alt="Screenshot 2024-07-22 at 6 18 54 PM" src="https://github.com/user-attachments/assets/fb58333d-f766-4d55-829e-f348793b99e7">

<img width="1582" alt="350675603-41c7936c-949e-41de-85df-16419206e21e" src="https://github.com/user-attachments/assets/f4e09a89-05c2-40c3-a021-aff9a23ada81">

I think `vite.config.js` is the culprit here. It serving correct directory on `npm run dev` but wrong upon `npm run build`

```js
import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import { svelte } from "@sveltejs/vite-plugin-svelte";

export default defineConfig(({ command }) => {
    const isBuild = command === "build";
    return {
        base: isBuild ? "/public/build/" : "/",
        plugins: [
            laravel({
                publicDirectory: "storage/public",
                input: [
                    "storage/inertia/css/app.css",
                    "storage/inertia/js/app.js",
                ],
                ssr: "storage/inertia/js/ssr.js",
                refresh: true,
            }),
            svelte({
                compilerOptions: {
                    hydratable: true,
                },
            }),
        ],
    };
});

```

**Comment by tahyhax** [comment]
@harryqt Give me the permissions to create a PR. In your repo

**Comment by harryqt** [comment]
Invite sent.
